dist: trusty

language: php

php:
    - 5.5
    - 7

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

stages:
  - code

jobs:
  include:
    - stage: code
      name: "PHPCS check"
      script: composer lint

script: composer test

after_success:
    - bash <(curl -s https://codecov.io/bash)
